"""add user_id to user_queries

Revision ID: af038ddfa095
Revises: 3a75f00ff838
Create Date: 2026-05-10 21:01:52.829724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af038ddfa095'
down_revision: Union[str, Sequence[str], None] = '3a75f00ff838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_queries', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_queries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_queries', type_='foreignkey')
    op.drop_column('user_queries', 'user_id')
    # ### end Alembic commands ###
