"""init tables

Revision ID: d3f9c4af4907
Revises: 
Create Date: 2026-03-25 17:54:15.758170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f9c4af4907'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('primary_category', sa.String(length=50), nullable=True),
    sa.Column('subjects', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id')
    )
    op.create_table('user_queries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('expanded_queries_json', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('vector_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('gap', sa.Text(), nullable=True),
    sa.Column('methods_json', sa.Text(), nullable=True),
    sa.Column('datasets_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_topics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('datasets', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_topics')
    op.drop_table('extracted_facts')
    op.drop_table('article_embeddings')
    op.drop_table('user_queries')
    op.drop_table('articles')
    # ### end Alembic commands ###
